[book]
authors = ["Tanvir Rahman"]
language = "bn"
src = "src"
title = "গিট ও গিটহাব শিখি বাংলায়"
description = "গিট ও গিটহাব শিখি বাংলায় — একদম শুরু থেকে গিট এবং গিটহাব শেখার একটি পূর্ণাঙ্গ ওপেন সোর্স বাংলা গাইড।"

[output.html]
git-repository-url = "https://github.com/tanvir-cpp/learn-git-bangla"
site-url = "https://git.tanvirrahman.me/"
edit-url-template = "https://github.com/tanvir-cpp/learn-git-bangla/edit/main/{path}"

[output.html.google-analytics]
id = "G-5PP2B7Y286"
